"""Static source rows captured from the approved v2 GMP/ISO 22000 workbook.

This module is intentionally data-only. It lets Taj Core prove that every source
checklist requirement is represented even when repeated requirements are reused
as one canonical Checklist Question across multiple area templates.
"""

GMP_SOURCE_ROWS = [{'area': 'Receiving',
  'source_no': 1,
  'question': 'Are floors, walls, lights/light fixtures, doors and receiving structures clean and in good condition?',
  'category': 'Building & Facilities',
  'iso_clause': '7.1.3 / 8.2.4(a)',
  'frequency': 'week 1 & 3'},
 {'area': 'Receiving',
  'source_no': 2,
  'question': 'Is the receiving area free from standing water, waste and unnecessary materials?',
  'category': 'Hygiene & Sanitation',
  'iso_clause': '7.1.4 / 8.2.4(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Receiving',
  'source_no': 3,
  'question': 'Are receiving doors kept closed when not in use and protected against pest entry?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Receiving',
  'source_no': 4,
  'question': 'Are fly catcher units clean, operational and free from excessive insect accumulation?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Receiving',
  'source_no': 5,
  'question': 'Are rodent trap boxes present, intact, secured and unobstructed?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Receiving',
  'source_no': 6,
  'question': 'Are pest trap labels/identification numbers present, legible and correct?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Receiving',
  'source_no': 7,
  'question': 'Is the area free from pest activity or pest evidence?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Receiving',
  'source_no': 8,
  'question': 'Are receiving equipment, racks, pallets and containers free from rust, corrosion, flaking metal or '
              'damaged surfaces?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Receiving',
  'source_no': 9,
  'question': 'Are cleaning tools clean, intact and stored in the designated location?',
  'category': 'Cleaning Tools',
  'iso_clause': '8.2.4(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Receiving',
  'source_no': 10,
  'question': 'Are cleaning chemicals correctly labelled, closed and stored away from food materials?',
  'category': 'Chemical Control',
  'iso_clause': '8.2.4(h),(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Receiving',
  'source_no': 11,
  'question': 'Are air curtain units and/or plastic strip curtains, where installed, clean, intact, properly '
              'positioned and functioning effectively?',
  'category': 'Building & Facilities / Pest Prevention',
  'iso_clause': '7.1.3 / 8.2.4(a),(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Receiving',
  'source_no': 12,
  'question': 'Is the area free from equipment or tools not designated for use in this area?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 1,
  'question': 'Are floors, walls, lights/light fixtures, ceilings and doors clean and in good condition?',
  'category': 'Building & Facilities',
  'iso_clause': '7.1.3 / 8.2.4(a)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 2,
  'question': 'Is the store clean, dry and free from leakage or condensation?',
  'category': 'Hygiene & Sanitation',
  'iso_clause': '7.1.4 / 8.2.4(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 3,
  'question': 'Are materials stored off the floor with adequate clearance for cleaning and inspection?',
  'category': 'Storage GMP',
  'iso_clause': '8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 4,
  'question': 'Are materials properly covered or sealed when not in use?',
  'category': 'Contamination Prevention',
  'iso_clause': '8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 5,
  'question': 'Are raw materials clearly labelled with sufficient identification such as item name and batch/lot '
              'information?',
  'category': 'Identification / Traceability',
  'iso_clause': '8.3 / 8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 6,
  'question': 'Are opened raw materials labelled with opening/date identification where applicable?',
  'category': 'Identification',
  'iso_clause': '8.3 / 8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 7,
  'question': 'Are allergenic materials properly identified and segregated?',
  'category': 'Cross-contamination',
  'iso_clause': '8.2.4(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 8,
  'question': 'Are fly catcher units clean and operational where installed?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 9,
  'question': 'Are rodent trap boxes intact, secured and unobstructed?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 10,
  'question': 'Are pest trap labels/identification numbers present and legible?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 11,
  'question': 'Is the area free from insects, rodents, droppings or pest evidence?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 12,
  'question': 'Are racks, shelves, containers and storage equipment free from rust, corrosion or flaking surfaces?',
  'category': 'Equipment / Storage GMP',
  'iso_clause': '8.2.4(e),(g),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 13,
  'question': 'Are air curtain units and/or plastic strip curtains, where installed, clean, intact, properly '
              'positioned and functioning effectively?',
  'category': 'Building & Facilities / Pest Prevention',
  'iso_clause': '7.1.3 / 8.2.4(a),(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 14,
  'question': 'Is the area free from equipment or tools not designated for use in this area?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Dry Store',
  'source_no': 15,
  'question': 'are there any material store directly under the chilling unit.',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(g), (h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 1,
  'question': 'Are floors, walls, lights/light fixtures, ceilings, doors and racks clean and intact?',
  'category': 'Building & Facilities',
  'iso_clause': '7.1.3 / 8.2.4(a)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 2,
  'question': 'Are raw and cooked/RTE materials physically segregated?',
  'category': 'Cross-contamination',
  'iso_clause': '8.2.4(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 3,
  'question': 'Are stored products properly covered and protected from contamination?',
  'category': 'Storage GMP',
  'iso_clause': '8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 4,
  'question': 'Are raw materials clearly labelled and identifiable?',
  'category': 'Identification / Traceability',
  'iso_clause': '8.3 / 8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 5,
  'question': 'Are sub-processed/intermediate items clearly labelled with product name, batch/date or other required '
              'identification?',
  'category': 'Identification / Traceability',
  'iso_clause': '8.3 / 8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 6,
  'question': 'Are unidentified or incorrectly labelled materials absent from the chiller?',
  'category': 'Identification Control',
  'iso_clause': '8.3',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 7,
  'question': 'Is the chiller free from excessive condensation, leaks and standing water?',
  'category': 'Hygiene & Facilities',
  'iso_clause': '7.1.4 / 8.2.4(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 8,
  'question': 'Is adequate space maintained around stored products for cleaning and airflow?',
  'category': 'Storage GMP',
  'iso_clause': '8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 9,
  'question': 'Are spills and food residues removed promptly?',
  'category': 'Cleaning & Sanitation',
  'iso_clause': '8.2.4(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 10,
  'question': 'Are pest monitoring points, where installed, intact, accessible and correctly identified?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 11,
  'question': 'Is the area free from pest evidence?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 12,
  'question': 'Are racks, shelves, containers and handling equipment free from rust, corrosion or flaking surfaces?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 13,
  'question': 'Are air curtain units and/or plastic strip curtains, where installed, clean, intact, properly '
              'positioned and functioning effectively?',
  'category': 'Building & Facilities / Pest Prevention',
  'iso_clause': '7.1.3 / 8.2.4(a),(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 14,
  'question': 'Is the area free from equipment or tools not designated for use in this area?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Chiller',
  'source_no': 15,
  'question': 'are there any material store directly under the chilling unit.',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(g), (h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 1,
  'question': 'Are floors, walls, lights/light fixtures, ceilings, doors and racks clean and maintained?',
  'category': 'Building & Facilities',
  'iso_clause': '7.1.3 / 8.2.4(a)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 2,
  'question': 'Are products properly wrapped, covered and protected from contamination?',
  'category': 'Storage GMP',
  'iso_clause': '8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 3,
  'question': 'Are products stored off the floor and arranged to allow cleaning access?',
  'category': 'Storage GMP',
  'iso_clause': '8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 4,
  'question': 'Are raw materials clearly labelled and identifiable?',
  'category': 'Identification / Traceability',
  'iso_clause': '8.3 / 8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 5,
  'question': 'Are sub-processed/intermediate materials clearly labelled and identifiable?',
  'category': 'Identification / Traceability',
  'iso_clause': '8.3 / 8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 6,
  'question': 'Are unidentified products absent from the freezer?',
  'category': 'Identification Control',
  'iso_clause': '8.3',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 7,
  'question': 'Is excessive ice or frost accumulation absent?',
  'category': 'Hygiene & Facilities',
  'iso_clause': '7.1.4 / 8.2.4(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 8,
  'question': 'Are leaking or damaged packs segregated?',
  'category': 'Contamination Prevention',
  'iso_clause': '8.2.4(g),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 10,
  'question': 'Is the freezer free from pest evidence?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 11,
  'question': 'Are racks, shelves, containers and handling equipment free from rust, corrosion or damaged metal '
              'surfaces?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 12,
  'question': 'Are air curtain units and/or plastic strip curtains, where installed, clean, intact, properly '
              'positioned and functioning effectively?',
  'category': 'Building & Facilities / Pest Prevention',
  'iso_clause': '7.1.3 / 8.2.4(a),(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 13,
  'question': 'Is the area free from equipment or tools not designated for use in this area?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Freezer',
  'source_no': 14,
  'question': 'are there any material store directly under the chilling unit.',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(g), (h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Preparation Area',
  'source_no': 1,
  'question': 'Are floors, walls, lights/light fixtures, ceilings and drains clean and in good condition?',
  'category': 'Building & Facilities',
  'iso_clause': '7.1.3 / 8.2.4(a)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 2,
  'question': 'Are food-contact surfaces clean and sanitized (non active production)',
  'category': 'Cleaning & Sanitation',
  'iso_clause': '8.2.4(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 3,
  'question': 'Are utensils and equipment clean, intact and free from contamination? (non-active production',
  'category': 'Equipment Hygiene',
  'iso_clause': '8.2.4(e),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 4,
  'question': 'Are raw and cooked/RTE materials adequately separated? (non active production',
  'category': 'Cross-contamination',
  'iso_clause': '8.2.4(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 5,
  'question': 'Are sub-processed items clearly labelled and identifiable when temporarily stored or held?',
  'category': 'Identification / Traceability',
  'iso_clause': '8.3 / 8.2.4(g)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 6,
  'question': 'Are colour-coded utensils and cutting boards correctly used where applicable?',
  'category': 'Cross-contamination',
  'iso_clause': '8.2.4(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 7,
  'question': 'Are waste bins clean, controlled and emptied regularly?',
  'category': 'Waste Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 8,
  'question': 'Are chemicals stored away from food and food-contact equipment?',
  'category': 'Chemical Control',
  'iso_clause': '8.2.4(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 9,
  'question': 'Are utensils, tables, equipment and food containers free from rust, corrosion, pitting or flaking '
              'metal?',
  'category': 'Equipment Hygiene / Foreign Material Control',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 10,
  'question': 'Are cleaning chemicals correctly labelled and kept in approved containers?',
  'category': 'Chemical Control',
  'iso_clause': '8.2.4(h),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 11,
  'question': 'Are cleaning tools clean, intact and stored in their designated rack/location?',
  'category': 'Cleaning Tools',
  'iso_clause': '8.2.4(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 12,
  'question': 'Are cleaning tools colour-coded/dedicated to the correct area where applicable?',
  'category': 'Cross-contamination / Sanitation',
  'iso_clause': '8.2.4(h),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 13,
  'question': 'Are cleaning tools stored off the floor and allowed to dry hygienically?',
  'category': 'Cleaning Tools',
  'iso_clause': '8.2.4(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 14,
  'question': 'Is the area free from glass, brittle plastic, loose metal or foreign-material risks?',
  'category': 'Foreign Material Control',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 15,
  'question': 'Are fly catcher units clean, operational and free from excessive insect accumulation?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 16,
  'question': 'Are pest trap labels/identification numbers present and legible?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 17,
  'question': 'Is the area free from pest activity or evidence?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 18,
  'question': 'Are air curtain units and/or plastic strip curtains, where installed, clean, intact, properly '
              'positioned and functioning effectively?',
  'category': 'Building & Facilities / Pest Prevention',
  'iso_clause': '7.1.3 / 8.2.4(a),(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Preparation Area',
  'source_no': 19,
  'question': 'Is the area free from equipment or tools not designated for use in this area?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 1,
  'question': 'Are floors, walls, lights/light fixtures, ceilings and drains clean and maintained?',
  'category': 'Building & Facilities',
  'iso_clause': '7.1.3 / 8.2.4(a)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 2,
  'question': 'Are cooking vessels and surrounding food-contact surfaces clean before use?',
  'category': 'Cleaning & Sanitation',
  'iso_clause': '8.2.4(e),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 3,
  'question': 'Are cooking vessels, utensils, equipment and food containers free from rust, corrosion, pitting or '
              'flaking metal?',
  'category': 'Equipment Hygiene / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 4,
  'question': 'Are sub-processed/cooked items held in the area clearly labelled and identifiable?',
  'category': 'Identification / Traceability',
  'iso_clause': '8.3 / 8.2.4(g)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 5,
  'question': 'Is the area free from excessive condensation or dripping above exposed food?',
  'category': 'Contamination Prevention',
  'iso_clause': '7.1.4 / 8.2.4(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 6,
  'question': 'Are ventilation and extraction systems clean and functioning adequately?',
  'category': 'Utilities / Facilities',
  'iso_clause': '7.1.4 / 8.2.4(c)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 7,
  'question': 'Are employees following personal hygiene and protective clothing requirements?',
  'category': 'Personnel Hygiene',
  'iso_clause': '8.2.4(j)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 8,
  'question': 'Are waste, food residues and spillages removed promptly?',
  'category': 'Cleaning & Sanitation',
  'iso_clause': '8.2.4(d),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 9,
  'question': 'Are cleaning tools clean, intact and stored in the designated location?',
  'category': 'Cleaning Tools',
  'iso_clause': '8.2.4(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 10,
  'question': 'Are cleaning tools dedicated/colour-coded correctly where applicable?',
  'category': 'Cross-contamination',
  'iso_clause': '8.2.4(h),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 11,
  'question': 'Are cleaning chemicals clearly labelled and stored away from exposed food?',
  'category': 'Chemical Control',
  'iso_clause': '8.2.4(h),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 12,
  'question': 'Are chemical containers free from leakage and unauthorized transfer into unlabelled containers?',
  'category': 'Chemical Control',
  'iso_clause': '8.2.4(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 13,
  'question': 'Are fly catcher units clean, operational and positioned to avoid contamination?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 14,
  'question': 'Are pest trap labels/identification numbers present and legible?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 15,
  'question': 'Is the area free from pest activity or pest evidence?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 16,
  'question': 'Are air curtain units and/or plastic strip curtains, where installed, clean, intact, properly '
              'positioned and functioning effectively?',
  'category': 'Building & Facilities / Pest Prevention',
  'iso_clause': '7.1.3 / 8.2.4(a),(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Cooking Area',
  'source_no': 17,
  'question': 'Is the area free from equipment or tools not designated for use in this area?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 1,
  'question': 'Are floors, walls, lights/light fixtures, ceilings and drains clean and in good condition?',
  'category': 'Building & Facilities',
  'iso_clause': '7.1.3 / 8.2.4(a)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 2,
  'question': 'Is the area clean and free from unnecessary materials?',
  'category': 'Hygiene & Housekeeping',
  'iso_clause': '7.1.4 / 8.2.4(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 3,
  'question': 'Are fillers, conveyors, tables and food-contact surfaces cleaned and sanitized?',
  'category': 'Cleaning & Sanitation',
  'iso_clause': '8.2.4(e),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 4,
  'question': 'Are operators following required hand hygiene and protective clothing practices?',
  'category': 'Personnel Hygiene',
  'iso_clause': '8.2.4(j)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 5,
  'question': 'Are exposed products protected from environmental contamination?',
  'category': 'Cross-contamination',
  'iso_clause': '8.2.4(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 6,
  'question': 'Are trays, pouches and lids stored and handled hygienically?',
  'category': 'Packaging Hygiene',
  'iso_clause': '8.2.4(f),(g)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 7,
  'question': 'Are any sub-processed/intermediate items in the area clearly labelled and identifiable?',
  'category': 'Identification / Traceability',
  'iso_clause': '8.3 / 8.2.4(g)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 8,
  'question': 'Are retort baskets, trolleys and handling equipment clean and maintained?',
  'category': 'Equipment Hygiene',
  'iso_clause': '8.2.4(e),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 9,
  'question': 'Are fillers, conveyors, trolleys, retort baskets, containers and related equipment free from rust, '
              'corrosion, pitting or flaking metal?',
  'category': 'Equipment Hygiene / Foreign Material Control',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 10,
  'question': 'Is the retort area free from standing water, debris and uncontrolled waste?',
  'category': 'Housekeeping',
  'iso_clause': '8.2.4(d),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 11,
  'question': 'Are cleaning tools clean, intact and stored hygienically?',
  'category': 'Cleaning Tools',
  'iso_clause': '8.2.4(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 12,
  'question': 'Are cleaning tools dedicated/colour-coded to the correct area where applicable?',
  'category': 'Cross-contamination',
  'iso_clause': '8.2.4(h),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 13,
  'question': 'Are hoses and cleaning tools stored off the floor after use?',
  'category': 'Cleaning Tools',
  'iso_clause': '8.2.4(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 14,
  'question': 'Are cleaning chemicals clearly labelled and kept in designated storage?',
  'category': 'Chemical Control',
  'iso_clause': '8.2.4(h),(i)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 15,
  'question': 'Are chemical containers closed, intact and free from leakage?',
  'category': 'Chemical Control',
  'iso_clause': '8.2.4(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 16,
  'question': 'Are fly catcher units clean, operational and appropriately positioned?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 17,
  'question': 'Are rodent trap boxes, where installed, intact, secured and unobstructed?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 18,
  'question': 'Are pest trap labels/identification numbers present and legible?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 19,
  'question': 'Is the area free from pest activity or pest evidence?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 20,
  'question': 'Are air curtain units and/or plastic strip curtains, where installed, clean, intact, properly '
              'positioned and functioning effectively?',
  'category': 'Building & Facilities / Pest Prevention',
  'iso_clause': '7.1.3 / 8.2.4(a),(d)',
  'frequency': 'week 2 & 4'},
 {'area': 'Filling & Retort Area',
  'source_no': 21,
  'question': 'Is the area free from equipment or tools not designated for use in this area?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 2 & 4'},
 {'area': 'Incubation Area',
  'source_no': 1,
  'question': 'Is the incubation room clean, dry and structurally maintained?',
  'category': 'Building & Facilities',
  'iso_clause': '7.1.3 / 8.2.4(a),(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 2,
  'question': 'Are products stored orderly with sufficient clearance for cleaning?',
  'category': 'Storage GMP',
  'iso_clause': '8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 3,
  'question': 'Are products/batches clearly labelled and identifiable?',
  'category': 'Identification / Traceability',
  'iso_clause': '8.3',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 4,
  'question': 'Are different batches arranged to prevent mix-up?',
  'category': 'Storage / Handling',
  'iso_clause': '8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 5,
  'question': 'Are leaking or damaged packs segregated?',
  'category': 'Contamination Prevention',
  'iso_clause': '8.2.4(g),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 6,
  'question': 'Are racks, shelves and product-holding equipment free from rust, corrosion or flaking surfaces?',
  'category': 'Equipment / Storage GMP',
  'iso_clause': '8.2.4(e),(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 7,
  'question': 'Are cleaning tools clean and properly stored?',
  'category': 'Cleaning Tools',
  'iso_clause': '8.2.4(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 8,
  'question': 'Are cleaning chemicals correctly labelled and segregated from products?',
  'category': 'Chemical Control',
  'iso_clause': '8.2.4(h),(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 9,
  'question': 'Are rodent trap boxes, where installed, intact, secured and unobstructed?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 10,
  'question': 'Are pest trap labels/identification numbers present and legible?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 11,
  'question': 'Is the area free from insects, rodents or other pest evidence?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 12,
  'question': 'Are walls, lights/light fixtures, racks and floors free from dust and accumulated debris?',
  'category': 'Cleaning & Sanitation',
  'iso_clause': '8.2.4(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 13,
  'question': 'Are air curtain units and/or plastic strip curtains, where installed, clean, intact, properly '
              'positioned and functioning effectively?',
  'category': 'Building & Facilities / Pest Prevention',
  'iso_clause': '7.1.3 / 8.2.4(a),(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Incubation Area',
  'source_no': 14,
  'question': 'Is the area free from equipment or tools not designated for use in this area?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 1,
  'question': 'Are floors, walls, lights/light fixtures, ceilings, doors and racks clean and maintained?',
  'category': 'Building & Facilities',
  'iso_clause': '7.1.3 / 8.2.4(a)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 2,
  'question': 'Is the warehouse clean, dry and free from leaks or condensation?',
  'category': 'Hygiene & Sanitation',
  'iso_clause': '7.1.4 / 8.2.4(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 3,
  'question': 'Are finished products stored off the floor and protected from contamination?',
  'category': 'Storage GMP',
  'iso_clause': '8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 4,
  'question': 'Is adequate clearance maintained around pallets for cleaning and pest inspection?',
  'category': 'Storage / Pest Control',
  'iso_clause': '8.2.4(d),(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 5,
  'question': 'Are stored finished products clearly labelled and identifiable?',
  'category': 'Identification / Traceability',
  'iso_clause': '8.3 / 8.2.4(g)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 6,
  'question': 'Are damaged cartons, trays or pouches segregated?',
  'category': 'Contamination Prevention',
  'iso_clause': '8.2.4(g),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 7,
  'question': 'Are racks, shelves, pallets and handling equipment free from rust, corrosion or flaking surfaces?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 8,
  'question': 'Are cleaning tools clean, intact and stored in their designated location?',
  'category': 'Cleaning Tools',
  'iso_clause': '8.2.4(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 9,
  'question': 'Are cleaning tools stored separately from finished products?',
  'category': 'Contamination Prevention',
  'iso_clause': '8.2.4(h),(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 10,
  'question': 'Are cleaning chemicals clearly labelled and stored away from finished products?',
  'category': 'Chemical Control',
  'iso_clause': '8.2.4(h),(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 11,
  'question': 'Are fly catcher units, where installed, clean and operational?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 12,
  'question': 'Are rodent trap boxes at designated locations intact, secured and unobstructed?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 13,
  'question': 'Are pest trap labels/identification numbers present and matching the pest-control layout?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 14,
  'question': 'Is the warehouse free from insects, rodents, droppings or other pest evidence?',
  'category': 'Pest Control',
  'iso_clause': '8.2.4(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 15,
  'question': 'Are loading and dispatch areas maintained clean and protected from contamination?',
  'category': 'Dispatch Hygiene',
  'iso_clause': '8.2.4(g),(i)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 16,
  'question': 'Are air curtain units and/or plastic strip curtains, where installed, clean, intact, properly '
              'positioned and functioning effectively?',
  'category': 'Building & Facilities / Pest Prevention',
  'iso_clause': '7.1.3 / 8.2.4(a),(d)',
  'frequency': 'week 1 & 3'},
 {'area': 'Finished Goods Area',
  'source_no': 17,
  'question': 'Is the area free from equipment or tools not designated for use in this area?',
  'category': 'Equipment / Contamination Prevention',
  'iso_clause': '8.2.4(e),(h)',
  'frequency': 'week 1 & 3'}]

GMP_SOURCE_ROW_COUNT = len(GMP_SOURCE_ROWS)
